[2023-12-25T13:12:49.168+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.878+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.879+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-25T13:12:52.046+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-18 00:00:00+00:00
[2023-12-25T13:12:52.097+0000] {standard_task_runner.py:60} INFO - Started process 424 to run task
[2023-12-25T13:12:52.120+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-07-18T00:00:00+00:00', '--job-id', '496', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpcudl9al5']
[2023-12-25T13:12:52.147+0000] {standard_task_runner.py:88} INFO - Job 496: Subtask Extract
[2023-12-25T13:12:54.613+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T13:12:54.782+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_flow.Extract scheduled__2023-07-18T00:00:00+00:00 [running]> on host b33131cfaa7f
[2023-12-25T13:13:50.190+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-25T13:13:53.344+0000] {process_utils.py:131} INFO - Sending 15 to group 424. PIDs of all processes in the group: [424]
[2023-12-25T13:13:54.537+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 424
